Add --for-packaging option.
Used only with --local-lib-contained, it attempts to install only runtime
requirements in the local lib. All test, config, and build requirements are
installed in standard site destination. The idea is to install everything iun
a directory that can be bundled up and distributed, minimizing the amount of
unnecessary stuff to include for a purely runtime use case.

There are a couple of issues working againsrt this plan, however:

 *   Not all distributions properly specify requirements. Older distributions,
     in particular, just list everything in the `PREREQ_PM` section of the
     `Makefile.PL`, and therefor must be assumed to be runtime. See the
     Devel-Caller `Makefile.PL` for an example:
     https://metacpan.org/source/RCLAMP/Devel-Caller-2.06/Makefile.PL.

 *   There are bugs. I think I got most of it worked out, but when I tried to
     use it with the Sqitch `./Build bundle` command, it ran into an error
     when trying to install B::Hooks::OP::Check:

     ````
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     ERROR: Can't create '/B/Hooks/OP'
     mkdir /B: Permission denied at /Users/david/.plenv/versions/5.28.0/lib/perl5/5.28.0/

     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     ```

     Presumably I've just overlooked some config that needs to be overridden.

 I think it's close, enough to give the idea, and might be worth revisiting or
 cribbing from at some point.